apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:RJ8Lb1wKQrgy8pRK7AMxqgLEQo6iQb5uzQ==,iv:hr3OGLOizR93CpQUlpE14+EJHyr2q+bg3/uB/1Hlgm4=,tag:GcWCVlA5UUV+30mzYwizmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-17T00:39:34Z"
    mac: ENC[AES256_GCM,data:E3g2RLKyGFzkAo83mUJqpJz6CoBDdxrI2E5E83JIlGt0ZmQ5c55zqjXxGhFIw9hJaA3vIhurX9ezhbauyhvj733leLN1dYuquKmR6UayLBRL2X593t04bazdzMw98+cFr1mRJVsxhwY95wA46evv5iGKYjgwN+MzUFQ3B0oCTLo=,iv:Cw5WLpx/wJowmNV9q/J8SA3pLrhgsLBBZmZOuY5avgc=,tag:tXWDPeEuYnb0cSqGaOwETQ==,type:str]
    pgp:
        - created_at: "2024-12-17T00:39:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA2/kVcyXkMl6AQv8DFELNWCFRAhVpV0TeBBQ1TqLx9+ixVuTMqS+ImdM1POU
            t0INPJ5I6E3p/UXoG7fVaTb2GP3rTEq1/zb5jASYRELdOFN3A1S1x+vgL+0ZGu1G
            XK7+y3OcURIJzu+9dt8XowP/mWhh7CM+47Z/cpKrU8xJ22WawvVbONpF/plH/IIz
            1R2M1ekobEbu22HU8hsM77YQP7+Hcus09waBz83hGDvPWSiMUzYjVcUp658Cs7Se
            IWWYmoHHB5xsfNjJtKwJl5/dUq/Im0QP04dvoc9tb1Eh8+mXEz/jTMhEaCrEk9SZ
            s5Sv9JDT8lRGlV1Lcmg+tjVnMfB4cDIKiW9D8f6UeNruWzZb+M7O1m0CjeHkuECA
            JCy/iOv8Srhf4tJqM1+rPmQ6aORNWveliYgjlpUH8zwQNpPayWP8Ab2rW2sp/KCh
            su9hxisPjJVwcvOqAwChG5BiztsOy253utbbRsjIuQc9wx744U/l548BoBk/6VOh
            8LhR1fLN0Op4BOn6URig0l4BS9re1R9++RtNTgnNnGnCyLcniGa/9Dj1dQcof8W2
            KKOmc1p7wsLy1eP468MYCWWWb9qAUXFXjiC+UiJPLbgESYVzyuOESIpCHdQJdns7
            keLbRtXe9jYPYQQ9bEoL
            =XpPH
            -----END PGP MESSAGE-----
          fp: A606FA8F3F61F2BB
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
